name: 'listrepo_in_org'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_target:
    types: [labeled]

jobs:
  run:
    name: Repo list generator
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.event == 'push' }} ||
      ${{ github.event.event == 'workflow_dispatch' }} ||
      contains(github.event.pull_request.labels.*.name, 'wait-to-merge')
    steps:
      - name: Checkout Code
        id: repo
        uses: Chakriwipro/Test-project-3@v1.0.1
        with:
          my_token: ${{ secrets.REPO_TOKEN }}
           # (default)user: ${{ github.repository }}
           # (default)max_page: 10
           # (default)block_list:
           # (default)allow_empty: false

      - name: Echo Output
        run: |
          echo repo: ${{steps.repo.outputs.repo}}
          echo repoList: ${{steps.repo.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo.outputs.privateList}}
          echo forkList: ${{steps.repo.outputs.forkList}}
          echo emptyList: ${{steps.repo.outputs.emptyList}}
