name: 'listrepo_in_org'

on: [push, fork]

jobs:
  any_name:
    name: Repo list generator
    runs-on: ubuntu-latest
    steps:
      - name: get the secrect key  
        id: repo
        with:
          my_token: ${{ secrets.REPO_TOKEN }}

      - name: list out private repos
        shell: bash
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/orgs/wipro-philips/repos?type=private | grep html_url
